### ISSUE TITLE
De-duplicate dependency lists

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/pynitrokey#111]
As far as I see, we currently have three dependency lists, `ci-requirements.txt`, `dev-requirements.txt` and `pyproject.toml`.  From my understanding, the lists in `ci-requirements.txt` and `pyproject.toml` should be identical.  It would be easier to maintain if that list was only defined in one place.

**Comment by szszszsz** [comment]
`pipenv` allows to define multiple dependencies' lists AFAIK. Would be nice if any tool we choose would handle `pyproject.toml`.
Quick comparison I have found:
- https://frostming.com/2021/03-26/pm-review-2021/

**Comment by robin-nitrokey** [comment]
Good pointer, thanks.  Maybe we should start by compiling a list of which tool uses which config file.

**Comment by robin-nitrokey** [comment]
I think the easiest solution would be to add a `dev` extra with the development dependencies.  Then we should be able to only use `flit install` for installing the dependencies, either with or without the `dev` extra.  We could remove the text files and only use the `pyproject.toml` file for the dependencies.  We wouldn’t even have to introduce any new tooling.

**Comment by szszszsz** [comment]
Nice. If it does so, then let's switch to it.
In the longer perspective I think we should plan for some dependency "locking" package manager anyway, like the mentioned.

**Comment by robin-nitrokey** [comment]
Implemented in #172.
