### ISSUE TITLE
Consider simple GUI and/or one-shot command for nk3 firmware update

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/pynitrokey#141]
Probably as a standalone project that is using the pynitrokey API.

cc @daringer @szszszsz

**Comment by szszszsz** [comment]
For Windows a single frame, self-contained UI app with single button and a progress bar would be perfect

**Comment by daringer** [comment]
The designated tool for this is: https://github.com/Nitrokey/nitrokey-app2 - also with pre-build binaries here: https://github.com/Nitrokey/nitrokey-app2/releases
