### ISSUE TITLE
Fix udev rules message

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/pynitrokey#171]
[Broken link](https://www.nitrokey.com/documentation/installation#p:nitrokey-fido2&os:linux) in [`check_root`](https://github.com/Nitrokey/pynitrokey/blob/master/pynitrokey/cli/__init__.py#L42):

```
"For more information, see: https://www.nitrokey.com/documentation/installation#p:nitrokey-fido2&os:linux"
```

**Comment by robin-nitrokey** [comment]
I started working on a new guide for docs.nitrokey.com [here](https://github.com/robin-nitrokey/nitrokey-documentation/blob/nitropy/software/nitropy/linux/udev.rst).

**Comment by szszszsz** [comment]
How to access that page?

**Comment by robin-nitrokey** [comment]
It’s not yet available, waiting for feedback from @daringer.

**Comment by robin-nitrokey** [comment]
I’ve created a draft PR for easier tracking: https://github.com/Nitrokey/nitrokey-documentation/pull/80

**Comment by szszszsz** [comment]
@dvzrv Unfortunately yes, due to a bug in CI. Sorry about that. I will make another release today.
