### ISSUE TITLE
Windows: cannot execute due to the missing Python libraries

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#188]
After installation through installer I cannot execute pynitrokey from console (or file browser) due to the missing Python libraries.

Found at:
- https://github.com/Nitrokey/pynitrokey/pull/176#issuecomment-1032727753

Exact message:
> nitropy.exe - System Error
> The code execution cannot proceed because python36.dll was not found. Reinstalling the program may fix this problem.

Edit: setting as medium, since there is a workaround by using a standalone binary
Edit: single executable works

**Comment by robin-nitrokey** [comment]
Unfortunately, I don’t see any related messages in the build log and I can’t find any similar issues.

**Comment by szszszsz** [comment]
On Windows the binary from the installer still complains about missing `python3.6.dll`. Tested both .17 and .18.
