### ISSUE TITLE
Check for the own updates

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#198]
Add check for the own updates when calling firmware update operation for any model, and warn user in case there is a newer release available.
The motivation is here to make sure, that the latest update procedure is used, or at least the user is warned that the new release is available. The check for the latest firmware is done anyway, thus this will not make any unexpected network calls.

To reiterate, the check for the own updates should be done *only on the firmware update operation calls* (regardless of the model), not on the every invocation.

Cases, where this would help avoid problems:
- https://support.nitrokey.com/t/update-nk3-not-working/3950/10?u=szszszsz

**Comment by Laborratte5** [comment]
I would try to implement this

**Comment by daringer** [comment]
There already is a min pynitrokey version in the firmware-update container: https://github.com/Nitrokey/pynitrokey/blob/0cfa85d2ebd15eac2044573516ec9a2907e9a05d/pynitrokey/nk3/updates.py#L180

This could be extended to inform the user about the most recent available version

**Comment by Laborratte5** [comment]
So it should be checked wether the current pynitrokey version is older 
than the latest version (as per git tags)

and print a warning to the user if this is the case. Am I right?


As szszszsz stated:

 > when calling firmware update operation for any model


Just to be sure I dont miss any, is the following list complete?

- 
https://github.com/Nitrokey/pynitrokey/blob/master/pynitrokey/cli/update.py#L36

- 
https://github.com/Nitrokey/pynitrokey/blob/master/pynitrokey/cli/nk3/__init__.py#L420

- 
https://github.com/Nitrokey/pynitrokey/blob/master/pynitrokey/nethsm/__init__.py#L1075

- 
https://github.com/Nitrokey/pynitrokey/blob/master/pynitrokey/cli/nethsm.py#L1174

- 
https://github.com/Nitrokey/pynitrokey/blob/master/pynitrokey/cli/pro.py#L113

- 
https://github.com/Nitrokey/pynitrokey/blob/master/pynitrokey/cli/start.py#L187

- 
https://github.com/Nitrokey/pynitrokey/blob/master/pynitrokey/cli/storage.py#L145

**Comment by Laborratte5** [comment]
Just to be sure I understood everything right:
It should be checked wether the current pynitrokey version is older than the latest version (as per e.g. git tags)
and print a warning to the user if this is the case.

Second, as szszszsz stated:
> when calling firmware update operation for any model


Just to be sure I don't miss any, is the following list of update operations (where the version should be checked) complete?
https://github.com/Nitrokey/pynitrokey/blob/0cfa85d2ebd15eac2044573516ec9a2907e9a05d/pynitrokey/cli/update.py#L36
https://github.com/Nitrokey/pynitrokey/blob/0cfa85d2ebd15eac2044573516ec9a2907e9a05d/pynitrokey/cli/nk3/__init__.py#L420
https://github.com/Nitrokey/pynitrokey/blob/0cfa85d2ebd15eac2044573516ec9a2907e9a05d/pynitrokey/cli/pro.py#L113
https://github.com/Nitrokey/pynitrokey/blob/0cfa85d2ebd15eac2044573516ec9a2907e9a05d/pynitrokey/cli/start.py#L187
https://github.com/Nitrokey/pynitrokey/blob/0cfa85d2ebd15eac2044573516ec9a2907e9a05d/pynitrokey/cli/storage.py#L145

I'm unsure which one is the correct one in the case of the following two:
https://github.com/Nitrokey/pynitrokey/blob/0cfa85d2ebd15eac2044573516ec9a2907e9a05d/pynitrokey/nethsm/__init__.py#L1075
https://github.com/Nitrokey/pynitrokey/blob/0cfa85d2ebd15eac2044573516ec9a2907e9a05d/pynitrokey/cli/nethsm.py#L1174

**Comment by robin-nitrokey** [comment]
Thanks for looking into this!  From my point of view, we can omit the NetHSM because we only call a simple REST API endpoint that is not very likely to change or cause issues.  For the NK3, we now have a mechanism to ensure a minimum pynitrokey version so I’m not sure if we need this additional check.  We should discuss this tomorrow and get back to you to make sure that we’re on the same page here.

**Comment by robin-nitrokey** [comment]
Okay, so we would like to add this for the pro, storage, start and fido2 update initially.  Users should be warned if their installation is outdated but should be able to continue at their own risk.  There already is some code to check the latest release of a GitHub repository in `pynitrokey.updates` that you should be able to re-use (something like `Repository("Nitrokey", "pynitrokey").get_latest_release()`).

**Comment by Laborratte5** [comment]
> should be able to continue at their own risk

How should I go about this?
Should there be
- an interactive prompt like "continue with outdated version? [y/N]"
- an cli option like `--force` or `--ignore-version` similar to `--experimental` of `nitropy storage update` 
- an environment variable to allow ignoring outdated versions for scripting

In my opinion an combination of (cli parameter/environment variable) and interactive prompt seems optimal as it still allows ignoring the warning in e.g. scripts while still prompting users if they are sure to continue.

**Comment by robin-nitrokey** [comment]
From my point of view, an interactive prompt would be sufficient because updates should not be automated.  Though I see that `start update` already `-y` (yes) option.  @daringer Is this really a supported use case?

**Comment by daringer** [comment]
I guess `start update` is a "historically grown" feature :grin: 
I would also suggest to have an interactive prompt.

**Comment by Laborratte5** [comment]
Ok, so I only add the interactive prompt.
