### ISSUE TITLE
Unrelated information when accessing NetHSM

### ISSUE THREAD

**Issue by jans23** [Nitrokey/pynitrokey#208]
For accessing a NetHSM the following information is mostly irrelevant. Also the link to www.nitrokey.com/documentation/... is outdated and should be updated.

![Bildschirmfoto von 2022-03-09 21-24-46](https://user-images.githubusercontent.com/1450547/157529975-93e25643-6035-4238-8ac7-376bc7d219fd.png)

**Comment by szszszsz** [comment]
Udev rules screen is shown when pynitrokey is run with root privileges. We can check if nethsm subcommands are used, and disable such help for this particular call.

Connected: https://github.com/Nitrokey/pynitrokey/issues/171

**Comment by szszszsz** [comment]
I can't find the mentioned docs string anywhere - perhaps you use outdated version? Can you check?

**Comment by szszszsz** [comment]
Please reopen in case you have the latest version (0.4.19) and still experience this problem.
The update command is: `pip3 install -U pynitrokey`

I have added small changes in the meantime:
- show version in the welcome string
- describe how to hide check_root warning in the help screen

**Comment by jans23** [comment]
Right, the version is 0.4.9

**Comment by szszszsz** [comment]
Removed udev rules-related screen for NetHSM - see below example output, with `fido2` subcommand for comparison .

```
$ nitropy fido2 ls
Nitrokey tool for Nitrokey FIDO2, Nitrokey Start, Nitrokey 3 & NetHSM 0.4.19
THIS COMMAND SHOULD NOT BE RUN AS ROOT!

Please install udev rules and run `nitropy` as regular user (without sudo).
We suggest using: https://raw.githubusercontent.com/Nitrokey/libnitrokey/master/data/41-nitrokey.rules
For more information, see: https://docs.nitrokey.com/fido2/linux/index.html#troubleshooting

Set ALLOW_ROOT=1 environment variable to disable this warning.

Usage: nitropy fido2 [OPTIONS] COMMAND [ARGS]...
Try 'nitropy fido2 --help' for help.

Error: No such command 'ls'.
$ nitropy nethsm state
Nitrokey tool for Nitrokey FIDO2, Nitrokey Start, Nitrokey 3 & NetHSM 0.4.19
THIS COMMAND SHOULD NOT BE RUN AS ROOT!
Set ALLOW_ROOT=1 environment variable to disable this warning.

Usage: nitropy nethsm [OPTIONS] COMMAND [ARGS]...
Try 'nitropy nethsm --help' for help.

Error: Missing option '-h' / '--host'.

```
