### ISSUE TITLE
Document the need for Python 3.6

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#212]
Document the need for Python 3.6 minimal supported version

Connected:
- https://github.com/Nitrokey/pynitrokey/pull/121#issuecomment-1019248836
- https://github.com/Nitrokey/pynitrokey/pull/158

**Comment by szszszsz** [comment]
Also mentioned in #219

**Comment by szszszsz** [comment]
Pasting relevant comment from #224:
>  (...) apparently only the Windows build is holding us up. Looking at the last packages list for the given release we can safely move further to even Python 3.9.
- https://repology.org/project/python/badges

cc @robin-nitrokey

**Comment by robin-nitrokey** [comment]
We should also describe the platforms we want to support in the developer guide.  I think you answered that question previously, but I can’t find it atm.  I think latest Ubuntu and latest Ubuntu LTS?

**Comment by szszszsz** [comment]
Yes, writing that down would be good. I think we had in mind support 2 LTS distributions back, which would mean 20.04 right now. Let me confirm that.

**Comment by szszszsz** [comment]
@robin-nitrokey Only the current LTS, so 22.04.

**Comment by szszszsz** [comment]
Helpful resources to establish the supported version:
- https://repology.org/project/python/badges
- https://repology.org/badge/vertical-allrepos/python.svg

Looks like the oldest one is on the current stable Debian - Python 3.9.2.
