### ISSUE TITLE
Add environment information to the log

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#222]
Environment information is not always added to the logs. It would be desirable to have it for the Nitrokey 3 update process.
Currently it is implemented for Nitrokey Start, which could be moved to the main execution.

**Comment by robin-nitrokey** [comment]
environment info could be:
- operating system
- Python version
- architecture

**Comment by szszszsz** [comment]
Related: 
https://github.com/Nitrokey/pynitrokey/blob/d097213cb59560f7162c48574f7fb2f71ed96065/pynitrokey/start/upgrade_by_passwd.py#L527-L535
