### ISSUE TITLE
Fails to run with cryptography==37.0.2

### ISSUE THREAD

**Issue by nitro-rico** [Nitrokey/pynitrokey#223]
Current release fails to work with `cryptography==37.0.2`

#### Workaround
```
 pip3 install cryptography==36.0.2
```

**Comment by nitro-rico** [comment]
![Bildschirmfoto vom 2022-05-05 17-08-55](https://user-images.githubusercontent.com/102814659/166973386-77c98708-bff3-43ce-9884-b50813a8cb41.png)

**Comment by robin-nitrokey** [comment]
`spsdk` currently does not work with `cryptography` 37 (https://github.com/NXPmicro/spsdk/issues/42) and it drops Python 3.6 support, so we have to pin it to < 37.
