### ISSUE TITLE
Change Client SDK Attribute for Current API

### ISSUE THREAD

**Issue by nitro-rico** [Nitrokey/pynitrokey#227]
![image](https://user-images.githubusercontent.com/102814659/169805720-022a32a9-62e9-4463-8aa9-86762596b0a0.png)

**Comment by szszszsz** [comment]
Hi! Please provide text representation as well for, thank you!

**Comment by nitro-rico** [comment]
nitropy nethsm --host $NETHSM_HOST list-keys

Command line tool to interact with Nitrokey devices 0.4.21
[auth] User name for NetHSM nethsmdemo.nitrokey.com: admin
[auth] Password for user admin on NetHSM nethsmdemo.nitrokey.com: 
Keys on NetHSM nethsmdemo.nitrokey.com:

Critical error:
An unhandled exception occurred
	Exception encountered: ApiAttributeError("PublicKey has no attribute 'restrictions' at ['received_data']['restrictions']")

--------------------------------------------------------------------------------
Critical error occurred, exiting now
Unexpected? Is this a bug? Would you like to get support/help?
- You can report issues at: https://support.nitrokey.com/
- Writing an e-mail to support@nitrokey.com is also possible
- Please attach the log: '/tmp/nitropy.log.gxp_jk5_' with any support/help request!
- Please check if you have udev rules installed: https://docs.nitrokey.com/nitrokey3/linux/firmware-update.html#troubleshooting

**Comment by robin-nitrokey** [comment]
To fix this, we have to update the scheme definition in `nethsm-scheme.json`, generate the client code (see the `nethsm-client` target of the Makefile) and then update `pynitrokey` accordingly.

**Comment by robin-nitrokey** [comment]
Fixed by #240.
