### ISSUE TITLE
NetHSM: Add support for recent API changes

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/pynitrokey#229]
API changes as of 2022-05-23:
- Breaking changes
  - [x] `/keys POST`: changed response
  - [x] `/config/tls/csr.pem PUT`: changed to `POST`
  - [x] `PublicKey` changed (https://github.com/Nitrokey/pynitrokey/issues/227)
  - [x] `reset` renamed to `factory-reset`
- Non-breaking changes
  - [ ] `/keys GET`: new optional argument `filter`
  - [ ] `/keys POST`: new optional argument `tags`
  - [ ] `/keys/{KeyID} PUT`: new optional arguments `mechanisms`, `tags`
  - [ ] `/keys/{KeyID}/csr.pem POST`: only `commonName` is required
  - [x] `KeyMechanism`extended
  - [x] `DecryptMode` extended
  - [x] `KeyType` extended
- New endpoints
  - [x] `/keys/{KeyID}/restrictions/tags/{Tag} DELETE`
  - [x] `/keys/{KeyID}/restrictions/tags/{Tag} PUT`
  - [x] `/users/{UserID}/tags GET`
  - [x] `/users/{UserID}/tags/{Tag} DELETE`
  - [x] `/users/{UserID}/tags/{Tag} PUT`
  - [x] `/config/tls/generate POST`
  - [ ] `/keys/{KeyID}/encrypt POST`
- Other
  - [x] check whether the removal of `"produces": ["application/x-pem-file"],` affects the client
  - [x] check whether we can revert https://github.com/Nitrokey/pynitrokey/pull/81/commits/5880e6831b0abd2955b4a069433bfda91bb77d8a, https://github.com/Nitrokey/pynitrokey/pull/81/commits/365b91848c9e405d902688f640beb171a1d11766
  - [ ]  update description of required roles: users can access their own data, administrators can access all user data

**Comment by jans23** [comment]
`reset` has been renamed to `factory-reset` now.

**Comment by jans23** [comment]
Documentation has been updated too. (the 2nd "soon" point above)
