### ISSUE TITLE
nitropy fido2 verify fails when pin is set

### ISSUE THREAD

**Issue by ksy63** [Nitrokey/pynitrokey#230]
nitropy version 0.4.22
Device Firmware version: 2.4.0
Device name: Nitrokey Fido2

Running `nitropy fido2 verify` before a pin was set:

> nitropy fido2 verify
> Command line tool to interact with Nitrokey devices 0.4.22
> please press the button on your Nitrokey device
> Touch your authenticator to generate a credential...
> found device: Nitrokey FIDO2 2.x (<hex string omitted>)

Running `nitropy fido2 verify` after a pin was set:

> nitropy fido2 verify
> Command line tool to interact with Nitrokey devices 0.4.22
> please press the button on your Nitrokey device
> Touch your authenticator to generate a credential...
> Critical error:
> unexpected Fido2Client (CTAP) error
> 	Exception encountered: Client error: 2 - BAD_REQUEST (cause: Pin required but not provided)
> 
> --------------------------------------------------------------------------------
> Critical error occurred, exiting now
> Unexpected? Is this a bug? Would you like to get support/help?
> - You can report issues at: https://support.nitrokey.com/
> - Writing an e-mail to support@nitrokey.com is also possible
> - Please attach the log: '/tmp/nitropy.log.t8rzggck' with any support/help request!
> - Please check if you have udev rules installed: https://docs.nitrokey.com/nitrokey3/linux/firmware-update.html#troubleshooting

The critical error message appears immediately. A pin was not requested

The log file contains the following:

> DEBUG       root print: Critical error:
> DEBUG       root print: unexpected Fido2Client (CTAP) error
> ERROR       root
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/pynitrokey/cli/fido2.py", line 581, in verify
>     cert = nkfido2.find(serial, udp=udp).make_credential(fingerprint_only=True)
>   File "/usr/lib/python3.10/site-packages/pynitrokey/fido2/client.py", line 250, in make_credential
>     attestation_object = client.make_credential(
>   File "/usr/lib/python3.10/site-packages/fido2/client.py", line 510, in make_credential
>     att_obj, extension_outputs = self._do_make_credential(
>   File "/usr/lib/python3.10/site-packages/fido2/client.py", line 571, in _ctap2_make_credential
>     pin_protocol, pin_auth, internal_uv = self._get_auth_params(
>   File "/usr/lib/python3.10/site-packages/fido2/client.py", line 474, in _get_auth_params
>     token = self._get_token(permission, rp_id, pin, event, on_keepalive)
>   File "/usr/lib/python3.10/site-packages/fido2/client.py", line 454, in _get_token
>     raise PinRequiredError()
> fido2.client.PinRequiredError

Problem:

It seems the verify command does not request a pin and fails immediately.

**Comment by robin-nitrokey** [comment]
Thanks for the report!  #216 will fix this by adding PIN handling to the `verify` command.

**Comment by daringer** [comment]
fixed by #410
