### ISSUE TITLE
nk3: nrf52: validate-update reports unknown signature

### ISSUE THREAD

**Issue by lynxis** [Nitrokey/pynitrokey#263]
When doing a manual fetch & validate of the nrf52 firmware, the firmware is signed by unknown.
The only known signature is a testkey in [nrf52.py](https://github.com/Nitrokey/pynitrokey/blob/master/pynitrokey/nk3/bootloader/nrf52.py#L58)

```sh
> nitropy nk3 fetch-update --variant nrf52
Command line tool to interact with Nitrokey devices 0.4.27
Successfully downloaded firmware release v1.1.0 to ./firmware-nk3am-nrf52-v1.1.0.zip
> nitropy nk3 validate-update firmware-nk3am-nrf52-v1.1.0.zip
Command line tool to interact with Nitrokey devices 0.4.27
version:    v1.1.0
signed by:  unknown
```

I'm using archlinux with nitropy 0.4.27.

**Comment by robin-nitrokey** [comment]
Good catch, thanks for the report!  @daringer can you please add the production key (or send me the public key so that I can add it)?
