### ISSUE TITLE
pynitrokey >=0.4.26 not installable on Arm

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/pynitrokey#265]
On Arm systems, pip only installs pynitrokey up to version 0.4.25.  This is probably due to the indirect dependency `pc_ble_driver_py` (pulled in by `nrfutil`), see https://github.com/NordicSemiconductor/pc-ble-driver-py/issues/202.

Related issues:
- https://github.com/NordicSemiconductor/pc-nrfutil/issues/337
- https://github.com/NordicSemiconductor/pc-nrfutil/issues/361
- https://github.com/NordicSemiconductor/pc-ble-driver/pull/271

**Comment by runcom** [comment]
@robin-nitrokey is there any known workaround?

**Comment by robin-nitrokey** [comment]
Yes.  You should be able to install Python and pynitrokey in a Rosetta terminal (see e. g. [this discussion](https://stackoverflow.com/questions/71691598/how-to-run-python-as-x86-with-rosetta2-on-arm-macos-machine)).  Or you could build `pc_ble_driver_py` and `pc_ble_driver_py` from source and install the wheel with `pip` before installing `pynitrokey` (as described in [this comment](https://github.com/NordicSemiconductor/pc-nrfutil/issues/361#issuecomment-1042850463) – though you should be able to use the upstream master as the PR has been merged).

**Comment by monwarez** [comment]
This also block FreeBSD support to pynitrokey 0.4.25 (with local patches for libusbio 2.1.11, and a minimal patches for nitropy to launch on FreeBSD)

**Comment by chri2** [comment]
@daringer installation worked fine on a Purism Librem5 (aarch64). If this is really resolved https://docs.nitrokey.com/software/nitropy/all-platforms/installation#arm-not-supported should be updated.
