### ISSUE TITLE
Dependencies for pipx installation (Debian Linux)

### ISSUE THREAD

**Issue by Gisi0** [Nitrokey/pynitrokey#273]
Please list the dependencies you need to install on a clean Debian Linux. I mean there was a libsd...dev I have to install and something else.

Thank you

**Comment by robin-nitrokey** [comment]
These build dependencies were introduced by a new dependency in v0.4.28.  To make installation easier, we are going to make that dependency optional in the next release so that end users are not affected by it.

**Comment by robin-nitrokey** [comment]
For the record, the required dependencies are: `swig gcc libpcsclite-dev libpython3.9-dev`.
