### ISSUE TITLE
Device status information

### ISSUE THREAD

**Issue by devnull09** [Nitrokey/pynitrokey#279]
There seems to be no way to list the currently stored keys on a device, like e.g. the number of stored residential keys.
If possible, this would be quite useful especially to find out of there is still space available  for additional keys.
No idea what happens when a user tries to store more then 50 residential keys on a Nitrokey Fido2 device for example and it would be good to have a way to find out how many can still be stored on a particular device.

**Comment by szszszsz** [comment]
In general you can manage RKs through Google Chrome / Chromium browsers.
I agree it would be nice to have it in the Nitrokey provided tool. We have a solution, that needs to be finished yet:
- https://github.com/Nitrokey/pynitrokey/pull/216

cc @daringer

**Comment by robin-nitrokey** [comment]
`nitropy fido2 list-credentials` now prints the number of residential keys on the device and the number of available slots.
