### ISSUE TITLE
Install fails with subtle errors when tmp is mounted noexec

### ISSUE THREAD

**Issue by sdlarsen** [Nitrokey/pynitrokey#282]
Hi.

Had difficulties getting pynitrokey to install in a virtual environment (Python 3.11, with cython installed):
```
Collecting pyyaml>=3.12
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      /tmp/pip-build-env-fk5k86wk/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      failed to import Cython: /tmp/pip-build-env-fk5k86wk/overlay/lib/python3.11/site-packages/Cython/Compiler/Scanning.cpython-311-x86_64-linux-gnu.so: failed to map segment from shared object
      error: Cython does not appear to be installed
      [end of output]
```

It turns out that this is due to /tmp being mounted noexec. Pointing TEMP elsewhere for the install, makes it run smoothly. This might save someone else a bit of time :)

**Comment by szszszsz** [comment]
Thank you for the tip! Worth adding to the doc.
For me installation on Python 3.11 does not work at all due to the dependency still requiring 3.10. It's interesting it was working for you - must be a recent change.

**Comment by AnanasPfirsichSaft** [comment]
I noticed this is also the case, if you try to run the static versions (nitropy-xxxx-x64-linux-binary) from the download area. The /tmp mount must be "exec". Otherwise you get "error while loading shared libraries: xxxxx: failed to map segment from shared object".

**Comment by daringer** [comment]
The official way to install should be [pipx](https://docs.nitrokey.com/software/nitropy/all-platforms/installation) haven't seen similar issues since - closing this issue - feel free to create a new one or re-open, if you still encounter this issue
