### ISSUE TITLE
Update pynitrokey installation

### ISSUE THREAD

**Issue by WebSchw** [Nitrokey/pynitrokey#283]
Using the installation as shown in the README doesn't give me the newest files as shown in this repo.

The issue that remained lied with the FIDO2 test which was still passing the PIN variable to "make_credential()".

I manually solved it by replacing the code in the respective test.py

I assume some repo that is called during the installation process needs to be refreshed - but dunno tbh.

**Comment by robin-nitrokey** [comment]
Please share the output of these commands:

```
$ nitropy version
$ python3 --version
$ python3 -m platform
```

**Comment by WebSchw** [comment]
```
$ nitropy version
Command line tool to interact with Nitrokey devices 0.4.23
0.4.23
$ python3 --version
Python 3.7.0
$ python3 -m platform
Linux-5.4.0-131-generic-x86_64-with-debian-bullseye-sid
```

Python 3.9 is installed but seems to be ignored by nitropy or at least it is not clear how to provide the python version.

**Comment by robin-nitrokey** [comment]
Yes, the original bug is fixed in newer pynitrokey versions but these require Python 3.9.  How did you install pynitrokey?

**Comment by WebSchw** [comment]
I tried `pipx install pynitrokey` like suggested on main page but also `pip3 install pynitrokey` (which probably relies on Pyhton3.7)
Is there an extra pip command for 3.9?

**Comment by robin-nitrokey** [comment]
Probably `pipx` defaults to `python3` which is v3.7.  You can try explicitly setting the python executable with:

```
$ pipx install --python python3.9 pynitrokey
```

**Comment by WebSchw** [comment]
Yes that helped. Thanks, can be closed.
