### ISSUE TITLE
Windows MSI build not always working

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#29]
It looks like the MSI build for Windows distribution is not always working. 
To better describe setup process to avoid pitfalls. Ideally add to CI as well #15.

**Comment by szszszsz** [comment]
Issue came from the latest release of the MSI builder, hence the difference between setups. 
https://github.com/Nitrokey/pynitrokey/issues/33 should solve the problem.

**Comment by daringer** [comment]
To be precise:
* cxfreeze is working but the MSI is not created
* this is a [known bug in cxfreeze](https://github.com/marcelotduarte/cx_Freeze/issues/693)
* pinning the version to 6.2 worked, current git (master) should also work

**Comment by szszszsz** [comment]
Hi!
@daringer Could this be closed? This blocks the v0.4 release.

**Comment by daringer** [comment]
yep, can do.
`cxfreeze` can be kept at 6.2 for now, don't see a need for an update
