### ISSUE TITLE
Mark integration tests

### ISSUE THREAD

**Issue by dvzrv** [Nitrokey/pynitrokey#294]
Hi! When trying to package 0.4.31 for Arch Linux I noticed, that I could run some tests now.
Unfortunately they all seem to be integration tests, that require a hardware token to be around.

[python-pynitrokey-0.4.31-1-x86_64-check.log](https://github.com/Nitrokey/pynitrokey/files/10140713/python-pynitrokey-0.4.31-1-x86_64-check.log)

It would be great if these could be marked as integration tests (e.g. use `pytest.mark`) or to skip them if no device was found.
That way downstreams can run unit tests (I guess there are none currently :smiling_face_with_tear: ) on the implementation of pynitrokey, without requiring a hardware token to be present.

Going forward it would be great to have a high unit-test coverage on the code base, to ensure its robustness.

**Comment by szszszsz** [comment]
Hi!
Good point. I have not expected these will be executed automatically during the build. To correct.
