### ISSUE TITLE
NK3: After having set a password in otp app, nitropy does not ask for password and get/register operation fail

### ISSUE THREAD

**Issue by avaiss** [Nitrokey/pynitrokey#299]
I am currently testing the OTP feature of a NK3 A. Using `nitropy nk3 otp register` or `nitropy nk3 otp get` works well unless a password is set:

    $ nitropy nk3 otp register --experimental Test 4IHNQYUXMAQDJCYBOGLQI53XM433DS6T
    Command line tool to interact with Nitrokey devices 0.4.31
    $ nitropy nk3 otp show
    Command line tool to interact with Nitrokey devices 0.4.31
    b'Test'
    $ nitropy nk3 otp get --experimental Test
    Command line tool to interact with Nitrokey devices 0.4.31
    Timestamp: 2022-12-10T13:55:40 (1670676940), period: 30
    840880
    $ nitropy nk3 otp set-password --experimental
    Command line tool to interact with Nitrokey devices 0.4.31
    Password: 
    Repeat for confirmation: 
    Password set
    $ nitropy nk3 otp get --experimental Test
    Command line tool to interact with Nitrokey devices 0.4.31
    Device returns error: CTAP error: 0x01 - INVALID_COMMAND. This credential id might not be registered.
    $ nitropy nk3 otp register --experimental Other 4IHNQYUXMAQDJCYBOGLQI53XM433DS6T
    Command line tool to interact with Nitrokey devices 0.4.31
    Critical error:
    An unhandled exception occurred
	  Exception encountered: CtapError('CTAP error: 0x01 - INVALID_COMMAND')
    ...

Problem seems to be that `nitropy` does not detect a password is set, as it does not ask for one. This is checked [this way](https://github.com/Nitrokey/pynitrokey/blob/master/pynitrokey/nk3/otp_app.py#L364) with algorithm and challenge set in a `SELECT` response.

However, the algorithm seems to not be set in the response, as can be seen in this test

    >>> nitrokey = Nitrokey3Device.list()[0]
    >>> app = OTPApp(nitrokey, logfn=print)
    >>> resp = app.select()
    Sending '00a4040007a0000005272101'
    Received '79030404047108e457a08a0392e046740811f6df6f9445eec3'
    >>> resp
    SelectResponse(version=b'\x04\x04\x04', name=b'\xe4W\xa0\x8a\x03\x92\xe0F', challenge=b'\x11\xf6\xdfo\x94E\xee\xc3', algorithm=None)
    >>> import tlv8
    >>> import codecs
    >>> resd: tlv8.EntryList = tlv8.decode(codecs.decode('79030404047108e457a08a0392e046740811f6df6f9445eec3', 'hex_codec'))
    >>> for x in resd:
    ...     print(x.type_id)
    ...     print(x.data)
    ... 
    121
    b'\x04\x04\x04'
    113
    b'\xe4W\xa0\x8a\x03\x92\xe0F'
    116
    b'\x11\xf6\xdfo\x94E\xee\xc3'

No entry with TLV id 7b (123) has been received.

I am not sure if this is a problem in the firmware, in the set_code command or in the `authentication_required` (like no algorithm means sha1), so I create my ticket here.

[nitropy.txt](https://github.com/Nitrokey/pynitrokey/files/10200148/nitropy.txt)

**Comment by szszszsz** [comment]
Hi! Thank you for the report!
The oath-authenticator app in this alpha release is outdated (v0.3.0), and the required changes are already introduced. Hopefully this will be released in the next alpha.
See details of the releases here:
- https://github.com/Nitrokey/oath-authenticator/releases

I do not know, why this information was missed in the blog announcement. @daringer Can you update the article please?
- https://www.nitrokey.com/blog/2022/nitrokey-3-alpha-firmware

Either way, nothing to do for pynitrokey. Closing.
