### ISSUE TITLE
nk3 list resident SSH FIDO2 keys

### ISSUE THREAD

**Issue by aieri** [Nitrokey/pynitrokey#308]
I can't seem to find a way to list resident SSH keys I have generated on my nitrokey3.

```
$ nitropy fido2 list  # nk3 not considered a fido2 key
Command line tool to interact with Nitrokey devices 0.4.31
:: 'Nitrokey FIDO2' keys
$ nitropy nk3 otp show
Command line tool to interact with Nitrokey devices 0.4.31
Authentication failed with error: "CTAP error: 0x01 - INVALID_COMMAND"
Aborted!
```

The SSH agent can however correctly fetch them via `ssh-add -K` as expected.

**Comment by robin-nitrokey** [comment]
Support for listing residential keys in nitropy is not released yet.  But you can test it if you install from Git:

```
$ pipx install git+https://github.com/nitrokey/pynitrokey --suffix=-git
$ nitropy-git fido2 list-credentials
```

We will probably release a version with this feature early next year.

**Comment by robin-nitrokey** [comment]
`nitropy fido2 list-credentials` should now work with pynitrokey 0.4.32.
