### ISSUE TITLE
Add CLI arguments to log

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/pynitrokey#309]
To make it easier to interpret log files, we should add the command that is being executed.

**Comment by Laborratte5** [comment]
Does this mean the log file should contain something like `nitropy nk3 list`?
I would be happy to implement this (if I understood this correctly)

**Comment by szszszsz** [comment]
Yes, and ideally at the same time without any possible passwords for the safe publishing.

**Comment by Laborratte5** [comment]
I'm a bit unsure of how I should implement the exclusion of sensitive parameters.
Right now I have two ideas:
1. Define a global list containing all sensitive parameters and exclude these from logging
1. Create a decorator for each command function to log the cli-parameters and add an option to exclude certain parameters there
This way the parameter logging for each function has to be "turned on" explicitly.
This would mean if some new command gets implemented and the developer forgets about the logging, parameters for this command wouldn't get logged at all which also means there would be no sensitive data logged.

However in the first apporach it would be easier to see at a glance which parameters get excluded from logging.

**Comment by robin-nitrokey** [comment]
Thanks for working on this issue!  We plan to drop the command-line arguments for PINs and passwords and replace them with environment variables or prompts (https://github.com/Nitrokey/pynitrokey/issues/401).  So I think the first suggestion, having a blacklist of redacted options, is the best approach.  It should be easier to implement than the configuration per command while still leading to the same results.  The downside is the maintenance cost, but as we don’t want to add new PIN and password arguments, I think that is fine.
