### ISSUE TITLE
CTAP error: 0x01 - INVALID COMMAND while doing anything OTP

### ISSUE THREAD

**Issue by PureTryOut** [Nitrokey/pynitrokey#319]
Using the Nitrokey 3, I get `Authentication failed with error: "CTAP error: 0x01 - INVALID_COMMAND"` when trying to do anything OTP related like registering TOTP for a GitLab instance.
I'm using the instructions as provided by https://www.nitrokey.com/blog/2022/nitrokey-3-alpha-firmware and pynitrokey version 0.4.32.

Seeing TOTP being broken on my Nitrokey 2 Pro after a fall was the major reason I got the Nitrokey 3 in the first place, this is quite annoying :sweat_smile: I made sure to update the firmware before doing this and it's now running version 1.2.2.

**Comment by szszszsz** [comment]
Hi!
There is a protocol mismatch between the current pynitrokey and last alpha firmware. You can try to use the previous pynitrokey releases (e.g. v0.4.31) to talk to it. The protocol mismatch test was not implemented, as it was not meant to be used in the production yet.

The latest pynitrokey works properly only with the latest OTP app, which was not released yet in the alpha release (0.5.0 vs 0.3.0 in the last alpha). I will get back to you if I would get any details about the new alpha release date.

**Comment by szszszsz** [comment]
This is outdated with the soon alpha and stable firmware release (around this week). Closing like so.
