### ISSUE TITLE
Python 3.11 Support

### ISSUE THREAD

**Issue by zevlee** [Nitrokey/pynitrokey#330]
The issue is currently being tracked at https://github.com/NordicSemiconductor/pc-ble-driver-py/issues/230

In the meantime, is there a way to circumvent this dependency for [pynitrokey](https://github.com/Nitrokey/pynitrokey)? Like an option to self-build the [pc-ble-driver-py](https://github.com/NordicSemiconductor/pc-ble-driver-py) component when installing through `pipx`?

**Comment by robin-nitrokey** [comment]
Our plan is to fork `nrfutil` and remove the `pc-ble-driver-py` dependency as it is causing multiple issues and is not needed for our use case anyway.  I can’t give you an estimate on when this fork will be ready though.

It should be possible to manually build the missing wheels similar to this (but without patching `pc-ble-driver`):
https://github.com/NordicSemiconductor/pc-ble-driver-py/issues/202#issuecomment-1043871397
But this is nothing that we can document, test or support for `pynitrokey`.
