### ISSUE TITLE
Ask user to send logs on the update failure

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#34]
Ask user to send logs to support email on the update failure.
- [x] Nitrokey Start
- [x] Nitrokey FIDO2

**Comment by daringer** [comment]
currently any critical error leads to a banner output including:
* link to this *issues* page on github
* location of log-file 
* reminder to provide the log-file together with an issue description

will add the support e-mail address, might be more convenient for the end-user
