### ISSUE TITLE
Update/unpin fido2 dependency

### ISSUE THREAD

**Issue by dvzrv** [Nitrokey/pynitrokey#36]
Hi! I'm currently baking a package for Arch Linux. Unfortunately I'm running into integration problems with the fido2 dependency.

The fido2 package has been on > 0.7.3 since November 2019 and on Arch Linux we're currently already shipping 0.8.1.
It would be most awesome to update this dependency so that this tool can be packaged.

Currently I'm helping the process along by using this patch:

```
diff --git i/pynitrokey/client.py w/pynitrokey/client.py
index ae7141d..ee59d9d 100644
--- i/pynitrokey/client.py
+++ w/pynitrokey/client.py
@@ -23,7 +23,6 @@ from fido2.ctap import CtapError
 from fido2.ctap1 import CTAP1
 from fido2.ctap2 import CTAP2
 from fido2.hid import CTAPHID, CtapHidDevice
-from fido2.utils import Timeout
 from intelhex import IntelHex
 from pynitrokey import helpers
 from pynitrokey.commands import SoloBootloader, SoloExtension
@@ -135,8 +134,7 @@ class SoloClient:
     def send_data_hid(self, cmd, data):
         if not isinstance(data, bytes):
             data = struct.pack("%dB" % len(data), *[ord(x) for x in data])
-        with Timeout(1.0) as event:
-            return self.dev.call(cmd, data, event)
+        return self.dev.call(cmd, data)

     def exchange_hid(self, cmd, addr=0, data=b"A" * 16):
         req = SoloClient.format_request(cmd, addr, data)
```

However, I am not sure whether this is the right way to remove the dependency on the removed Timeout utility class or whether there are more inconsistencies.

**Comment by dvzrv** [comment]
Tinkering a bit more with the package, I realized that there are other inconsistencies irt fido2.
To be able to use a package manager to install this on Arch Linux an update to support the latest fido2 library would be much appreciated!

**Comment by szszszsz** [comment]
Hi!
Indeed. I believe there are some calling diff's as well. Will look.

**Comment by daringer** [comment]
continued in #40

**Comment by daringer** [comment]
fixed in #40 now, closing to tidy up issues towards 0.4

**Comment by dvzrv** [comment]
I'm not sure why #40 has not been rebased ontop of master?

Is there another pull request tracking this topic now?

**Comment by daringer** [comment]
yes, sorry this was all handled within https://github.com/Nitrokey/pynitrokey/pull/40 and generally the 0.4 release...
fido2 is unpinned now
