### ISSUE TITLE
improve udev rules "handling"

### ISSUE THREAD

**Issue by daringer** [Nitrokey/pynitrokey#366]
We should be better with recognizing not existing udev rules, I see the following options to be investigated:

* automatically search for the actual udev-rules file and inform the user that it is not existing
* ship udev-rules files together with pynitrokey (installation might often not be useful, but `nitropy utils install-udev-rules` might be a thing?
* on failed operations that most likely need udev-rules be more explicit with the error message
* include the udev-rules file so that package maintainers can actually build packages that include these

we could easily have multiple udev-rules-files installed on a system without them interfering, right? Even if they handle the same devices? (e.g., one from nitrokey-app, one from pynitrokey)

**Comment by szszszsz** [comment]
Partly a duplicate of https://github.com/Nitrokey/pynitrokey/issues/197.
The minimum is downloading the udev rules file to the CWD and list to user what needs to be executed.
Automatically installing to the system directory is not seen welcomed AFAIK.

Udev rules contain instructions to stop processing once the rule match, so multiple of them should not conflict. The only downside is to extend the processing time for other devices, having lower priority than this particular file.

**Comment by daringer** [comment]
This is a duplicate of: https://github.com/Nitrokey/pynitrokey/issues/386 which should be used to track this
Same applies to #197
