### ISSUE TITLE
Include udev rules in repository

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/pynitrokey#386]
As libnitrokey is not a required dependency and also not updated for newer products, we should move the udev rules to this repository.  This would also make life easier for package maintainers (see also https://github.com/Nitrokey/pynitrokey/issues/381).

**Comment by daringer** [comment]
Many ideas and proposals to be found in #366 and #197, using this issue to align on the steps forward

**Comment by robin-nitrokey** [comment]
We’ve decided to move the udev rules into a separate repository, https://github.com/Nitrokey/nitrokey-udev-rules, instead of adding them to pynitrokey directly so that they can be versioned, packaged, and installed independent of client applications like pynitrokey, nitrokey-app2, or others.  I will update and close this issue once there is a first release of the new repository.

**Comment by PureTryOut** [comment]
Packaged in Alpine Linux as https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/59861, thanks for the effort!

**Comment by robin-nitrokey** [comment]
Thanks, that was fast! :)  What happens if I try to install both libnitrokey and nitrokey-udev-rules?

**Comment by PureTryOut** [comment]
Currently they'll conflict, I still have to resolve that but I wanted to get this in now, there probably won't be a lot of people using both.

**Comment by robin-nitrokey** [comment]
The `pro` and `storage` subcommands still require libnitrokey.  I agree that they are probably only used by a small share of users but it would be great if that would still work.
