### ISSUE TITLE
Bootloader connection improvements

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#39]
Nitrokey Start update: improve connection process after bootloader upload:
- [x] repeat bootloader connection attempt
- [x] additional delay allowing for the bootloader to start
- [x] remove the misleading message about reinsertion for the bootloader connection failure

Connected: https://github.com/Nitrokey/nitrokey-start-firmware/issues/51
Details: https://support.nitrokey.com/t/nitrokey-start-update-funktioniert-nicht/2596/4

**Comment by szszszsz** [comment]
@daringer Hi! Could you take a look at this for the v0.4 release?

**Comment by daringer** [comment]
1) does up to 3 retries, while being chatty
2) delay introduced, which increases for each re-try
3) messages massively reworked, please see #40
