### ISSUE TITLE
Request for feedback on the python client

### ISSUE THREAD

**Issue by spacether** [Nitrokey/pynitrokey#400]
Hi there. I am the author of the openapi-generator python client which has now moved to https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
Your repo uses this client.
I want to make sure that I understand what is important to the end users of the python client. If you have some time can you provide some feedback on what features you value in the generator, any pain points, and what you would like improved?
If you could provide your feedback [here](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/issues/179) it would help with future improvements. Thank you!

**Comment by robin-nitrokey** [comment]
It’s been a while since we’ve created that code and it was probably still using an older version of openapi-generator-cli.  I first have to take a look at the recent changes and then I’ll get back to your questions.

**Comment by spacether** [comment]
Sure thing. The migration guide is here https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/blob/master/samples/openapi3/client/petstore/python/migration_2_0_0.md
and your experience with the older code can also be helpful if you want to share that too.

**Comment by nponsard** [comment]
I tried the latest version and it doesn't work with our current api specification, see https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/issues/237 .
