### ISSUE TITLE
FIDO2's HMAC not working

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#403]
Fido2's HMAC challenge-response is not working at the moment. Most probably due to use of the outdated `fido2` libraries API.

- report: https://github.com/Nitrokey/nitrokey-3-firmware/issues/281#issuecomment-1579204555

**Comment by daringer** [comment]
this is fixed by #410 - `fido2 challenge-response` works now after `fido2 make-credential`
