### ISSUE TITLE
Install fails  with dep pyyaml: AttributeError: cython_sources

### ISSUE THREAD

**Issue by noffsh** [Nitrokey/pynitrokey#421]
Installing pynitrokey fails due to old pyyaml 5.4.1. 

[cmd_2023-07-23_12.47.44_pip_errors.log](https://github.com/Nitrokey/pynitrokey/files/12138551/cmd_2023-07-23_12.47.44_pip_errors.log)

There is already an [issue](https://github.com/yaml/pyyaml/issues/724), but It seems, they are unwilling to maintain 5.4: https://github.com/yaml/pyyaml/pull/726#issuecomment-1640397938

Installing pynitrokey from master works, since the spsdk dependency has been updated and it doesn't require pyyaml anymore.

Is it possible to cut a new release?

**Comment by robin-nitrokey** [comment]
Thanks for the report.  I’ve released 0.4.39.  It should be available on PyPI soon.
