### ISSUE TITLE
Update cryptography to the latest

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#427]
Update cryptography to the latest version: 41+:
- https://pypi.org/project/cryptography/

**Comment by daringer** [comment]
This will include an update to `fido2 1.1.2` ...

as `fido2 1.1.0` needs:
```
fido2 1.1.0 depends on cryptography!=35, <40 and >=2.6
```
But `fido2 1.1.2` seems to work properly
