### ISSUE TITLE
`semver.Version` renaming to `semver.VersionInfo` breaks pynitrokey

### ISSUE THREAD

**Issue by daringer** [Nitrokey/pynitrokey#432]
even though the `semver` still documents that `Version` is to be used: https://pypi.org/project/semver/

the implementation changed to `VersionInfo` instead

**Comment by daringer** [comment]
Wrong! The `python-semver` package in ArchLinux is outdated: https://archlinux.org/packages/extra/any/python-semver/ ... so closing this issue

**Comment by tomschr** [comment]
Funny that I stumbled upon this issue by accident. :smile: 

@daringer I'm the maintainer of python-semver. Just wanted so say hello :wave: and to leave some (hopefully) helpful information.

Yes, it is correct, that the `VersionInfo` class was renamed to `Version`. The former is deprecated now, although version 3 still contains the old name. To make the migration to the new version a bit easier. However, don't rely on it, it will be removed in a future release. :wink: 

Keep in mind, version 2 of semver won't receive any updates anymore so I'd recommend to update to version 3 soon. Find more information in the [migration chapter](https://python-semver.readthedocs.io/en/latest/migration/migratetosemver3.html).

If you need more information, head over to the [semver project](https://github.com/python-semver/python-semver) and start a discussion, open an issue, or just say hello.

Happy coding!
