### ISSUE TITLE
Tagging scheme broken

### ISSUE THREAD

**Issue by dvzrv** [Nitrokey/pynitrokey#44]
Hi! I would like to package pynitrokey for Arch Linux.
Unfortunately the tagging scheme is now broken with using [v0.4](https://github.com/Nitrokey/pynitrokey/releases/tag/v0.4) instead of `v0.4.nitrokey`, as there are upstream [solo-python](https://github.com/solokeys/solo-python) related tags and nitrokey related tags in use in this repository and I am using a regular expression match against the nitrokey specific suffix.

Will tags from now on not have the suffixes anymore?
If not, please tag `v0.4` also as `v4.0.nitrokey`.
Thanks!

**Comment by szszszsz** [comment]
Hi! Thank you for noticing that!
Indeed, I think it should be `0.4.0.nitrokey`, so we would not conflict with upstream's tags. Same scheme is used with Nitrokey FIDO2. What's your view @daringer?

**Comment by daringer** [comment]
oops, yeah brings us to the whole "not being a fork anymore topic" ... but that's a second topic, will release a `v0.4.1.nitrokey` with some recent fixes (including #43) today. Then asap bring the fork topic to a higher prio...

**Comment by daringer** [comment]
Released 0.4.1 using tag: `v0.4.1.nitrokey`

**Comment by dvzrv** [comment]
https://www.archlinux.org/packages/community/any/python-pynitrokey/
