### ISSUE TITLE
broken chain of trust for releases

### ISSUE THREAD

**Issue by dvzrv** [Nitrokey/pynitrokey#45]
Hi! When trying to package pynitrokey 0.4 for Arch Linux I am running into several issues related to cryptographic authentication that prevent me from packaging pynitrokey:

* ~~the public key for `4C1449F1C9804176` (@daringer)  is not available on any known keyserver~~ (I am currently force-uploading the public key for `CC74B7120BFAA36FF42868724C1449F1C9804176` to all servers after [retrieving it from github](https://github.com/daringer.gpg))
* no [chain of trust](https://en.wikipedia.org/wiki/Chain_of_trust) has been established between `D9BAE35991DE5B22` (@szszszsz ) and  `4C1449F1C9804176` (@daringer). From a [TOFU](https://en.wikipedia.org/wiki/Trust_on_first_use) point-of-view one would trust @szszszsz key first and action from your side has to be taken so that outsiders can trust a new key

The allowed release managers of this software should be noted in the README in a signed commit (signed by @szszszsz ).
Apart from that:

a) if you introduce a new key of your own, the new key needs to be signed by the old key and the change should be announced in a signed commit altering/extending the README
b) if you introduce someone else's key, the new key can be signed by the original author's/release maintainer's key and the change should be announced in a signed commit (signed by the original author/release manager) altering/extending the README

**Comment by szszszsz** [comment]
Hi!
Fair points, will do!

**Comment by dvzrv** [comment]
Any news on this?

**Comment by szszszsz** [comment]
Hi @dvzrv ! Thank you for reminding and sorry for taking time. I have added a signed commit with "maintainers list" file, which should satisfy your concerns. If not please reopen.
