### ISSUE TITLE
macOS: OSError - Failed reading a response

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#49]
User reports failure in executing Nitrokey FIDO2 firmware update on ~~macOS 10.16~~ macOS 11.0.1 (macOS Big Sur), with the latest update pynitrokey (v0.4.2).
Stack trace from the exception below.

<details>
<summary> log (click to show) </summary>

```
❯ nitropy fido2 update
*** Nitrokey tool for Nitrokey FIDO2 & Nitrokey Start
Nitrokey FIDO2 firmware update tool
Platform: macOS-10.16-x86_64-i386-64bit
System: Darwin, is_linux: False
Python: 3.8.6
Saving run log to: /var/folders/69/4cm0rh_13g58xwdllrpcwmlc0000gn/T/nitropy.log.3ni78tyq

Starting update procedure for Nitrokey FIDO2...
Downloading latest firmware: 2.2.0.nitrokey (published at 2020-09-23T15:21:45Z)
Firmware saved to /var/folders/69/4cm0rh_13g58xwdllrpcwmlc0000gn/T/fido2_firmware.json
Downloaded firmware version: 2.2.0.nitrokey
Device connected:
204D3395344B: Nitrokey FIDO2 2.1.0
Firmware version: 2.1.0

This will update your Nitrokey FIDO2
Do you want to continue? [yes/no]: yes
Traceback (most recent call last):
  File "/Users/billy/Library/Python/3.8/lib/python/site-packages/fido2/_pyu2f/macos.py", line 451, in Read
    return self.read_queue.get(False)
  File "/usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/nitropy", line 8, in <module>
    sys.exit(nitropy())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/billy/Library/Python/3.8/lib/python/site-packages/pynitrokey/cli/update.py", line 141, in update
    if client.is_solo_bootloader():
  File "/Users/billy/Library/Python/3.8/lib/python/site-packages/pynitrokey/fido2/client.py", line 234, in is_solo_bootloader
    self.bootloader_version()
  File "/Users/billy/Library/Python/3.8/lib/python/site-packages/pynitrokey/fido2/client.py", line 147, in bootloader_version
    data = self.exchange(SoloBootloader.version)
  File "/Users/billy/Library/Python/3.8/lib/python/site-packages/pynitrokey/fido2/client.py", line 122, in exchange_u2f
    res = self.ctap1.authenticate(chal, appid, req)
  File "/Users/billy/Library/Python/3.8/lib/python/site-packages/fido2/ctap1.py", line 273, in authenticate
    response = self.send_apdu(ins=CTAP1.INS.AUTHENTICATE, p1=p1, data=data)
  File "/Users/billy/Library/Python/3.8/lib/python/site-packages/fido2/ctap1.py", line 233, in send_apdu
    response = self.device.call(CTAPHID.MSG, apdu)
  File "/Users/billy/Library/Python/3.8/lib/python/site-packages/fido2/hid.py", line 89, in call
    status, resp = self._dev.InternalRecv()
  File "/Users/billy/Library/Python/3.8/lib/python/site-packages/fido2/_pyu2f/hidtransport.py", line 308, in InternalRecv
    first_read = self.InternalReadFrame()
  File "/Users/billy/Library/Python/3.8/lib/python/site-packages/fido2/_pyu2f/hidtransport.py", line 300, in InternalReadFrame
    frame = self.hid_device.Read()
  File "/Users/billy/Library/Python/3.8/lib/python/site-packages/fido2/_pyu2f/macos.py", line 453, in Read
    raise OSError('Failed reading a response')
OSError: Failed reading a response
```

</details>

<details>

<summary> tools' log (as received from user) </summary>

```
170       DEBUG _pyu2f.hidtransport payload: [76, 78, 92, 206, 240, 225, 235, 231]
170       DEBUG _pyu2f.hidtransport sending packet: [255, 255, 255, 255, 134, 0, 8, 76, 78, 92, 206, 240, 225, 235, 231, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
179       DEBUG _pyu2f.hidtransport recv: [255, 255, 255, 255, 134, 0, 17, 76, 78, 92, 206, 240, 225, 235, 231, 2, 0, 0, 0, 2, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
180       DEBUG _pyu2f.hidtransport sending packet: [2, 0, 0, 0, 144, 0, 1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
186       DEBUG _pyu2f.hidtransport recv: [2, 0, 0, 0, 144, 0, 126, 0, 168, 1, 131, 102, 85, 50, 70, 95, 86, 50, 104, 70, 73, 68, 79, 95, 50, 95, 48, 108, 70, 73, 68, 79, 95, 50, 95, 49, 95, 80, 82, 69, 2, 130, 107, 104, 109, 97, 99, 45, 115, 101, 99, 114, 101, 116, 107, 99, 114, 101, 100, 80, 114, 111, 116, 101]
190       DEBUG _pyu2f.hidtransport recv: [2, 0, 0, 0, 0, 99, 116, 3, 80, 195, 158, 251, 166, 252, 244, 76, 62, 130, 139, 252, 74, 97, 21, 160, 255, 4, 165, 98, 114, 107, 245, 98, 117, 112, 245, 100, 112, 108, 97, 116, 244, 104, 99, 114, 101, 100, 77, 103, 109, 116, 245, 105, 99, 108, 105, 101, 110, 116, 80, 105, 110, 245, 5, 25]
194       DEBUG _pyu2f.hidtransport recv: [2, 0, 0, 0, 1, 4, 176, 6, 129, 1, 7, 20, 8, 24, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

</details>

**Comment by InternalLoss** [comment]
Correction (I’m the guy who emailed) - it’s macOS 11.0.1 (macOS Big Sur), it’s referred to as 10.16 internally on Intel for.. Apple reasons I don’t know

**Comment by szszszsz** [comment]
@daringer Hi! Any updates on that?
@InternalLoss Hi! Sorry for the delay. Do you still experience this issue?

**Comment by InternalLoss** [comment]
Hi - my apologies, I've since used the update website on a Windows machine to update to latest firmware; when a new update comes out I can check again

**Comment by szszszsz** [comment]
That would be great, thank you for the update @InternalLoss !

**Comment by InternalLoss** [comment]
Still getting this on macOS 11.4:
```
Starting update procedure for Nitrokey FIDO2...
Downloading latest firmware: 2.4.1.nitrokey (published at 2021-05-12T12:24:14Z)
Firmware saved to /var/folders/g3/2prwxc8j3yl9ydzzdmp3w7_r0000gn/T/fido2_firmware.json
Downloaded firmware version: 2.4.1.nitrokey
Device connected:
XXX: Nitrokey FIDO2 2.4.0
Firmware version: 2.4.0

This will update your Nitrokey FIDO2
Do you want to continue? [yes/no]: yes
Entering bootloader mode, please confirm with button on key!
Critical error:
problem switching to bootloader mode:
OSError('Failed reading a response')

--------------------------------------------------------------------------------
Critical error occurred, exiting now
Unexpected? Is this a bug? Do you would like to get support/help?
- You can report issues at: https://github.com/Nitrokey/pynitrokey/issues/
- Writing an e-mail to: support@nitrokey.com is also possible
- Please attach the log: '/var/folders/g3/2prwxc8j3yl9ydzzdmp3w7_r0000gn/T/nitropy.log.n6geg3vc' with any support/help request!
--------------------------------------------------------------------------------
```

[nitropy.log.n6geg3vc.txt](https://github.com/Nitrokey/pynitrokey/files/6608713/nitropy.log.n6geg3vc.txt)

**Comment by InternalLoss** [comment]
Can confirm that this has **not** fixed the bug, see attached files (I'm also about to update to macOS 12 beta):

[nitropy-sudo.txt](https://github.com/Nitrokey/pynitrokey/files/6618098/nitropy-sudo.txt)

[nitropy-nosudo.txt](https://github.com/Nitrokey/pynitrokey/files/6618100/nitropy-nosudo.txt)

**Comment by InternalLoss** [comment]
Can confirm this is still occurring on 0.4.4 - log attached.
[nitropy.log.txt](https://github.com/Nitrokey/pynitrokey/files/7121295/nitropy.log.txt)

**Comment by daringer** [comment]
mmmh, yeah the logged error stays the same, essentially this will be the reason:
```
2496      DEBUG  fido2.hid SEND: 04000000d10000
6500      ERROR fido2.hid.macos Unexpected run loop exit code: 3
6500      DEBUG       root print: Critical error:
6501      DEBUG       root print: problem switching to bootloader mode:
6501      ERROR       root Failed reading a response
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fido2/hid/macos.py", line 310, in read_packet
    return self.read_queue.get(False)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/queue.py", line 168, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pynitrokey/cli/update.py", line 133, in update
    client.enter_bootloader_or_die()
  File "/usr/local/lib/python3.9/site-packages/pynitrokey/fido2/client.py", line 308, in enter_bootloader_or_die
    self.enter_solo_bootloader()
  File "/usr/local/lib/python3.9/site-packages/pynitrokey/fido2/client.py", line 304, in enter_solo_bootloader
    self.send_data_hid(SoloBootloader.HIDCommandEnterBoot, "")
  File "/usr/local/lib/python3.9/site-packages/pynitrokey/fido2/client.py", line 111, in send_data_hid
    return self.dev.call(cmd, data, event)
  File "/usr/local/lib/python3.9/site-packages/fido2/hid/__init__.py", line 175, in call
    recv = self._connection.read_packet()
  File "/usr/local/lib/python3.9/site-packages/fido2/hid/macos.py", line 312, in read_packet
    raise OSError("Failed reading a response")
OSError: Failed reading a response
```


to me this looks like the error is originating from the `fido2` module, this does not necessary means it's its fault, but at this point I can't really tell what might be the reason for that...

how about the other fido2 commands, do they work ?

**Comment by szszszsz** [comment]
Hi @InternalLoss !
Thank you for the update. Another reason for this error could be, that tool does not receive a response from the device after successfully entering the bootloader mode (which it does immediately, discarding all the current communication).

Can you run the update two times in a sequence, after receiving the error? I assume here that the first call will change operation to the bootloader mode, and the second one will continue the update with the bootloader mode activated.

Just wanted to note, that this experiment should be safe for the Nitrokey FIDO2 device and in the worst case the firmware can be recovered through the web update interface.

**Comment by InternalLoss** [comment]
> how about the other fido2 commands, do they work ?
Yes, `list`, `status`, and `wink` all work.
Status:
```
00 03 168 168 00 200 05 100
00 03 181 181 00 200 05 100
00 03 194 194 00 200 05 100
00 03 207 207 00 200 05 100
01 04 220 02 00 200 05 100
00 03 233 233 00 200 05 100
```
(I pushed the button to make sure that it changed at some point)

> further, after the failed operation, can you check if the stick is in bootloader mode (should be listed as such on nitropy fido2 list)?

Seems no? If I hold the button for long enough, yes

> Can you run the update two times in a sequence, after receiving the error? I assume here that the first call will change operation to the bootloader mode, and the second one will continue the update with the bootloader mode activated.
Yes, I can! Logs for both times attached - `error.txt` was the time with failing to get a response (but after holding the button down for long enough, it did go into bootloader mode), and `success.txt` was shortly after.

It seems like the script just doesn't wait enough? I know I ran into this issue on the web script before, where the button seems to need to be held for longer than expected.
[success.txt](https://github.com/Nitrokey/pynitrokey/files/7163226/success.txt)
[error.txt](https://github.com/Nitrokey/pynitrokey/files/7163227/error.txt)

**Comment by szszszsz** [comment]
> It seems like the script just doesn't wait enough? I know I ran into this issue on the web script before, where the button seems to need to be held for longer than expected.

Looks like it! Thank you for confirming. So in the end this is UI / error handling issue, rather than problem with communication. 
To be corrected.

**Comment by daringer** [comment]
There is a possible fix here: https://github.com/Nitrokey/pynitrokey/tree/mac-update
To test, try something like this:
```
git clone https://github.com/Nitrokey/pynitrokey.git mytestdir
cd mytestdir
git checkout mac-update
make
venv/bin/nitropy fido2 update
```

The fix essentially just waits once such an error occurs and continues execution, not perfect, but might work.

**Comment by LennardBoediger** [comment]
> There is a possible fix here: https://github.com/Nitrokey/pynitrokey/tree/mac-update
> To test, try something like this:
> 
> ```
> git clone https://github.com/Nitrokey/pynitrokey.git mytestdir
> cd mytestdir
> git checkout mac-update
> make
> venv/bin/nitropy fido2 update
> ```
> 
> The fix essentially just waits once such an error occurs and continues execution, not perfect, but might work.

This did not work, the update still took 3 attempts.
[fido2-update.log](https://github.com/Nitrokey/pynitrokey/files/7196860/fido2-update.log)

**Comment by szszszsz** [comment]
From the logs:
```
problem flashing firmware:
Exception('Wrong channel')

problem flashing firmware:
OSError('Failed to write report to device: 3758097131')
```

**Comment by daringer** [comment]
@LennardBoedinger can you please try again, added a throttled retry loop now...

**Comment by InternalLoss** [comment]
My NitroKey has sadly decided to break (the PCB fell out of the plastic..), so I can no longer help test this as I don't have any other NitroKey FIDO2 devices.

**Comment by daringer** [comment]
haven't heard anything about macOS issues lately, this issue is quite old and a lot has changes since.
Please open a new issue with new logs using a current pynitrokey version if the issue still persists.
