### ISSUE TITLE
secrets: providing password through cli is bad

### ISSUE THREAD

**Issue by daringer** [Nitrokey/pynitrokey#492]
A user reported: 
> Using Password Safe via CLI isn't particularly convenient. When I use
> the command "secrets add-password --password TEXT", it saves the password
> into the zsh/bash history.

perfectly true. 
The consequence should be that `pynitrokey` should provide a more secure way to pass passwords.

**Comment by robin-nitrokey** [comment]
Related: https://github.com/Nitrokey/pynitrokey/issues/401

**Comment by daringer** [comment]
arrrr, forgot about this one, closing this then in favor of #401
