### ISSUE TITLE
replace pypemicro with opensource library

### ISSUE THREAD

**Issue by wrenix** [Nitrokey/pynitrokey#515]
pypemicro use binary / nonfree code:
https://github.com/nxp-mcuxpresso/pypemicro/issues/10

**Comment by robin-nitrokey** [comment]
We are investigating different ways how we can avoid pulling in unneeded dependencies like this one.  That being said, we don’t actually use this dependency.  So you should be fine with using a patched spsdk version that just removes this dependency until we have a better solution if that is an option for you.

**Comment by dvzrv** [comment]
It would maybe be worthwhile to chime in on the ticket for spsdk to voice your concerns there:
https://github.com/nxp-mcuxpresso/spsdk/issues/30

Patching this is unfortunately not really a transparent process as upstream creates a new release using one giant commit that changes the entire repo every time.
I'd be happy having not to patch spsdk.

**Comment by daringer** [comment]
we are looking forward to throw out `spsdk` https://github.com/Nitrokey/pynitrokey/pull/519 :dancers:

**Comment by robin-nitrokey** [comment]
The dependency has been removed in [v0.5.0](https://github.com/Nitrokey/pynitrokey/releases/tag/v0.5.0).
