### ISSUE TITLE
Relax dependency on spsdk to allow using 2.1.x?

### ISSUE THREAD

**Issue by johanneskastl** [Nitrokey/pynitrokey#528]
Currently spsdk is pinned to`<2.1` in the pyproject.toml file.

Could this be relaxed, to allow using versions 2.1.x? I had a quick glance and found lots of doc changes between 2.0.x and 2.1.x, but not many real code changes. If spsdk uses semantic versioning, there should not be major / breaking changes in those versions.

Thanks in advance!

Johanes

**Comment by robin-nitrokey** [comment]
Unfortunately, spsdk does not follow semver, see https://github.com/nxp-mcuxpresso/spsdk/issues/34, and 2.1 is indeed a breaking change, see https://github.com/Nitrokey/pynitrokey/pull/524.  The next pynitrokey release will fix this, either by merging the linked PR to make it compatible with spsdk 2.1, or by vendoring the required components of spsdk directly in pynitrokey, see https://github.com/Nitrokey/pynitrokey/pull/519.

**Comment by johanneskastl** [comment]
Thanks  a lot @robin-nitrokey that was quick! :-)
