### ISSUE TITLE
App Display of Secrets not Working

### ISSUE THREAD

**Issue by kathmm** [Nitrokey/pynitrokey#541]
When opening the app it displays an empty panel where the stored passwords should be. While knowing I have stored a TOTP and it was working prior to remove the Nitrokey 3 after use and plugging in once more the error/issue occurred. However if I run `nitropy nk3 secrets list` it outputs `01. M365 Totp/Sha1 touch required,PIN required` showing that the secret is still saved.

When trying to add a new secret with the same credential name it will also state within the app that a secret is already existing under the name and refuses to set up a new secret. The error message is also depicted below in a screenshot.

The screenshot directly below shows both the app displaying none while the terminal output shows that the secret is still present.

This was performed on macOS Sonoma.

<img width="973" alt="Screenshot 2024-05-14 at 10 49 56" src="https://github.com/Nitrokey/pynitrokey/assets/146935083/205d4327-5a99-45de-a34f-7a855ef028ad">

<img width="331" alt="Screenshot 2024-05-14 at 12 22 05" src="https://github.com/Nitrokey/pynitrokey/assets/146935083/30278b7a-e42b-4917-98f0-f968e16537b9">

**Comment by daringer** [comment]
Did you try activating the checkbox "Show Protected Passwords" below the secrets-list in NitrokeyApp2 ? Overall this is an intended feature that you only see non-pin-required secrets, if this checkbox isn't activated.

**Comment by kathmm** [comment]
Ah, I see it now and had completely missed it as previously tested keys it had been ticked and I hadn't unticked it. Will make note to pay attention to it. Thank you for such a quick response!
