### ISSUE TITLE
Nitrokey 3C NFC not found in Nitropy in Bootloader mode

### ISSUE THREAD

**Issue by BiggA94** [Nitrokey/pynitrokey#543]
Hi, I guess this is more of a pynitrokey issue rather than a firmware Issue, else I could add an Issue to the Firmware Repo.

I wanted to update my Nitrokey from v1.6.0 to 1.7.0.
I tried this in the Nitrokey App.
After I need to touch the Nitrokey, the Stick reboots in Bootloader mode and is not recognised anymore.
Then I tried the same with nitropy and ensured it is listed (`nitropy nk3 list`).
This also works.

An `nitropy nk3 reboot --bootloader` works as intended. 
The Nitrokey is visible in Windows with e.g. usbipd, Zadig etc.
And I can see the ID 20a0:42dd clearly.

An nitropy list throws an error afterwards.
Log is attached.
[nitropy.log.i158qdq9.txt](https://github.com/Nitrokey/pynitrokey/files/15456283/nitropy.log.i158qdq9.txt)

Also I think this is not related to the timing issues of the former problems with updating, since the device is not found, even after a while.

Everything is running on Windows 11.
Tried it with python 3.10 and 3.11

**Comment by daringer** [comment]
Can you confirm that you also tried running it as administrator?
Do you maybe have some usb-guard software running ? bitdefender or something which doesn't have the bootloader whitelisted?

**Comment by robin-nitrokey** [comment]
Closing as we need more information to diagnose the problem.  Please re-open and provide more details if you are still running into this issue.
