### ISSUE TITLE
Make nitropy aware its running in a qube; have it prompt user for device reassignation after changing bootloader mode

### ISSUE THREAD

**Issue by tlaurion** [Nitrokey/pynitrokey#549]
As of today per current documentation:
- QubesOS usb proxy deploys udev rules
- When updating firmware, nk switch from normal to bootloader mode, bootloader mode to normal mode
- When switching between modes, qubesos usage is not considered, and pynitrokey/nitropy (confusing) timeout

Desired:
- nitropy detecting qubesos usage and prompting user to reassign dongle from qubes usb proxy widget from dom0 to qube where nitropy is called instead of doing a timeout

This is confusing mostly every not so technical users.
Example: https://matrix.to/#/!pAlHOfxQNPXOgFGTmo:matrix.org/$7gcke5HYUNvD2gX9xZJ3lMN3CUU5-1QAFmy0iri5WZ0?via=matrix.org&via=nitro.chat&via=envs.net

**Comment by nestire** [comment]
this is done in the new Version 2.3.1
