### ISSUE TITLE
Utility: support quickly creating the Encrypted Volume partition

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#55]
Utility: support quickly creating the Encrypted Volume partition for the Nitrokey Storage.

**Comment by daringer** [comment]
fixed by this PR: https://github.com/Nitrokey/pynitrokey/pull/199

**Comment by szszszsz** [comment]
Note to add: creating the actual partition will not be implemented, as per internal discussion.
End-user should do it on his own with the available OS tools, similarly as with the flash storage devices.
