### ISSUE TITLE
Fails to run on a fresh install

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#57]
After installing in a fresh Docker container based on Ubuntu 20.10, `nitropy` fails to run. Details below.
It looks like the `fido2` dependency got updated recently, removing some internal symbols pynitrokey was using.

Potential solutions:
- pin `fido2` package dependency to previous one, 0.8.1;
- remove usage of the internal `fido2` symbol.

Error log:
```
Installing collected packages: cbor, six, pycparser, cffi, cryptography, pyserial, pygments, click, chardet, certifi, idna, urllib3, re
quests, fido2, ecdsa, intelhex, pyusb, pynitrokey
Successfully installed cbor-1.0.0 certifi-2020.12.5 cffi-1.14.4 chardet-4.0.0 click-7.1.2 cryptography-3.3.1 ecdsa-0.16.1 fido2-0.9.0 i
dna-2.10 intelhex-2.3.0 pycparser-2.20 pygments-2.7.4 pynitrokey-0.4.1 pyserial-3.5 pyusb-1.1.1 requests-2.25.1 six-1.15.0 urllib3-1.26
.2
(...)
Step 8/8 : RUN nitropy --version
 ---> Running in ea09abdc49b3
Traceback (most recent call last):
  File "/usr/local/bin/nitropy", line 5, in <module>
    from pynitrokey.cli import nitropy
  File "/usr/local/lib/python3.8/dist-packages/pynitrokey/cli/__init__.py", line 15, in <module>
    import pynitrokey.fido2.operations
  File "/usr/local/lib/python3.8/dist-packages/pynitrokey/fido2/__init__.py", line 7, in <module>
    import fido2._pyu2f
ModuleNotFoundError: No module named 'fido2._pyu2f'

```

**Comment by alt3r-3go** [comment]
FWIW, the same happens on current Fedora 33 as well, looks like that `fido2` update got picked up by distros.

**Comment by daringer** [comment]
Trying to avoid pinning versions here, as this will break rolling-release distros like ArchLinux. But should be easy to fix it, will do it tomorrow...

**Comment by daringer** [comment]
mmmh well, fido2 is breaking compatibility in every release currently, also this one is not so "easily" (at least partly) adapted as the last one, so I had to pin the version for now.
Closing this and tracking the whole "update to fido2 version"-story here: https://github.com/Nitrokey/pynitrokey/issues/60
