### ISSUE TITLE
udev rules: what to disable to prevent firmware updates?

### ISSUE THREAD

**Issue by boredsquirrel** [Nitrokey/pynitrokey#572]
Even though the touch sensor is somewhat of a barrier, having a udev rule lying around there, granting any unprivileged app write access to these keys, doesnt sound like a good idea.

I have a Nitrokey 3A-mini. How would I disable the ability to flash the firmware, while still being able to get keys and fido2 authentifications?

I dont know if Nitrokey Heads has any udev rules included or works without them. This could give a lead, that all udev rules could be disabled if one doesnt want to flash the firmware.

**Comment by robin-nitrokey** [comment]
These are the udev rules that we recommend: https://github.com/Nitrokey/nitrokey-udev-rules/blob/main/41-nitrokey.rules

You would need to remove the relevant bootloader lines, in your case the one containing `ATTRS{idVendor}=="20a0", ATTRS{idProduct}=="42e8"`.
