### ISSUE TITLE
Cannot install pynitrokey - Linux Mint 22 Cinnamon

### ISSUE THREAD

**Issue by albotroz** [Nitrokey/pynitrokey#581]
https://docs.nitrokey.com/software/nitropy/all-platforms/installation
Nitrokey Docs describe it quite simply.
Unfortunately, it is not simple.

OS: Linux Mint 22 Cinnamon
Nitrokey 3 USB-A NFC

Using:
`sudo apt install pipx && pipx ensurepath && pipx install pynitrokey`

```
pip failed to build package:
    pyscard

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    Package libpcsclite was not found in the pkg-config search path.
    Package 'libpcsclite', required by 'virtual:world', not found
    src/smartcard/scard/helpers.c:28:10: fatal error: winscard.h: Datei oder Verzeichnis nicht gefunden
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
    ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pyscard)

Error installing pynitrokey.
```

After restarting, pynitrokey is still not available.

**Comment by robin-nitrokey** [comment]
v0.6.0 added a new dependency that we will make optional in the next release.  If you don’t need the PIV functionality, you can just skip v0.6.0.  Otherwise, installing `libpcsclite-dev` should fix the problem, see: https://github.com/Nitrokey/pynitrokey/issues/579.
