### ISSUE TITLE
Outdated link to documentation

### ISSUE THREAD

**Issue by jans23** [Nitrokey/pynitrokey#584]
If pyscard is not available to nitropy, you might get the following error when trying to use the PIV functionality:

>    This command requires the pyscard library that is not available on your system. Please consult https://docs.nitrokey.com/nitrokey3/linux/troubleshooting#pyscard-is-not-available for more information

This link is outdated and correct is https://docs.nitrokey.com/nitrokeys/nitrokey3/troubleshooting#pyscard-is-not-available

**Comment by robin-nitrokey** [comment]
This has been fixed in https://github.com/Nitrokey/pynitrokey/commit/1f795ef9c0c6762624263756804356b9f15f9bb2.
