### ISSUE TITLE
Document better installation process

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#59]
Document better installation process, especially for the Raspberry PI case:
- Udev rules;
- avoiding using root;
- Python packages installation (system- or user-wide?).
See:
- https://support.nitrokey.com/t/nitokey-start-firmware-update-failed-device-or-firmware-missing/2855/5

**Comment by robin-nitrokey** [comment]
I think we have this covered by the [documentation on docs.nitrokey.com](https://docs.nitrokey.com/software/nitropy/index.html) – @szszszsz can we close this issue?

**Comment by szszszsz** [comment]
If this covers the doubts explained in the support ticket, then sure, let's close it!
