### ISSUE TITLE
update to fido2 library version 0.9

### ISSUE THREAD

**Issue by daringer** [Nitrokey/pynitrokey#60]
as the python-fido2 library broke backwards compatibility with 0.9 there is some work to be done in order to make it work with it. Maybe even wait for 1.0 ?

**Comment by dvzrv** [comment]
An update would be much appreciated, as pynitrokey is currently not usable on Arch Linux due to this incompatibility.

**Comment by szszszsz** [comment]
@daringer @robin-nitrokey Can you look into that?

Setting high priority, since application cannot be run and used in some environments.

**Comment by szszszsz** [comment]
Potential pointers in the upstream (perhaps ready to merge):
- https://github.com/solokeys/solo-python/commit/b8be4572518c70515e2b63888e8b746dbf0ea7c4
- https://github.com/solokeys/solo-python/commit/096a9401c31b3882fdf45d78f5de0c2d872f0725
- https://github.com/solokeys/solo-python/commit/4d0a4fd4d50c9148d11fdcc3c6c7fe6e501f784e
- https://github.com/solokeys/solo-python/commit/d76ce9f383f4c6de3a636498f3adc8efa37514e6
- https://github.com/solokeys/solo-python/commit/bd1366ca1bdd5ce317f3f1b69aa62971dcde38b4

**Comment by dvzrv** [comment]
Any updates on this?

**Comment by daringer** [comment]
There a some changes incoming, including a project renaming (separation of lib and cli-tool)....
eta: before the end of the week

**Comment by daringer** [comment]
fixed upstream and released in version 0.4.3.1
