### ISSUE TITLE
Allow to install and run in standalone setup

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#61]
Given last issues with dependencies #60 #57, it would be nice to have the final distribution either packaged to a single file (using some bundler), or allow it to be installed separately in a virtual environment (e.g. pipenv, poetry).

Edit: to clarify, single binary distribution includes AppImage and Flatpak. All major OSes should be supported (not necessarily by a single solution).

**Comment by dvzrv** [comment]
I understand the incentive behind this, however this is unfortunately nothing that works for downstream distributions.
On Arch Linux for example we have all the dependencies packaged.

As  a user of the fido2 package it is really the best solution IMHO to keep up-to-date with the upstream (tests for this can even be automated). Bundling dependencies usually leads to bit rot and a an eventual larger amount of work to increase the versions of all dependencies at once.

**Comment by szszszsz** [comment]
Sure! This is actually something else than https://github.com/Nitrokey/pynitrokey/issues/60. Here we would like to have a standalone package/binary for users, who either do not know Python packagement system, or do not want to mess anything in their environment by installing user-wide packages. At the same time we assume they do not have access to the tool by other means.

**Comment by szszszsz** [comment]
Setting this to low priority, since we do not have much demand for this feature at the moment.

**Comment by robin-nitrokey** [comment]
Our [recommended installation process](https://docs.nitrokey.com/software/nitropy/all-platforms/installation.html) now uses a virtual environment, so I think we can close this issue – @szszszsz?

**Comment by dvzrv** [comment]
FWIW, feel free to include the installation method for Arch Linux in your documentation (if you want to):

```
sudo pacman -S python-pynitrokey
```

**Comment by szszszsz** [comment]
The main idea behind this ticket was to make a single executable standalone binary/package, which would not require further network communication (like AppImage). Again, I have not heard about such requests anymore, hence I guess we could consider this outdated and close it.
Let's reopen otherwise.
