### ISSUE TITLE
0.4.2 not available as sdist on pypi.org

### ISSUE THREAD

**Issue by dvzrv** [Nitrokey/pynitrokey#62]
Hi! The sdist tarball for 0.4.2 is not available on pypi.org.

It would be nice, if you could upload it :)

**Comment by szszszsz** [comment]
Hi @dvzrv !
Thank you for pointing that out! I have just uploaded the latest version to pypi. 
For the future, do you know if there is an unstable channel on pypi? I see, that some projects just use another name, with `unstable` suffixed. I wonder if this is accepted approach.

**Comment by dvzrv** [comment]
I guess it is always acceptable to use e.g. [semver'](https://semver.org/#semantic-versioning-specification-semver)s notion of pre-releases.

I don't really know how/if pip handles pre-release versions though.

**Comment by szszszsz** [comment]
Will check, thank you!
