### ISSUE TITLE
nitropy fills /tmp with empty log files

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/pynitrokey#68]
On every run, nitropy creates a log file which is typically empty if there are no log messages.  I suggest to only create log files if requested by the user, or at least only if there are messages to log.

**Comment by szszszsz** [comment]
As a workaround, we can remove the log file at the end of the execution if it looks empty.
Logging is useful mostly for the update process - it can be switched off for other operations, unless requested by user.

Logging only on the user request for all operations might be too late in case the update has failed, and the device under process resulted in an unknown state, hence I would be against it.

**Comment by robin-nitrokey** [comment]
I think it should be possible to only create the log file if there are log messages by setting `delay=True` for the [`FileHandler`](https://docs.python.org/3/library/logging.handlers.html#filehandler) instance [here](https://github.com/Nitrokey/pynitrokey/blob/master/pynitrokey/helpers.py#L63).

Also, what do you think about moving all initialization code, for example the banner message and the logger setup, into [`pynitrokey.cli.nitropy`](https://github.com/Nitrokey/pynitrokey/blob/master/pynitrokey/cli/__init__.py#L40)?  Currently, it is hard to see what is actually executed when `nitropy` runs.

**Comment by szszszsz** [comment]
1. `delay` sounds good!
2. I agree the initialization code is not properly structured. Please correct that.
