### ISSUE TITLE
Empty values while listing Nitrokey Start key

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#73]
> Hi! I'm having a problem updating my Nitrokey Start. The command `nitropy start list' outputs "'Nitrokey Start' keys: None: None None (None)".

> Never mind. I didn't have the required udev rules on the machine that I wanted to perform an update on

**Comment by daringer** [comment]
The solution here should be to check for the udev rules if running in Linux. Despite checking for the specific file in `/etc/udev/rules.d` I am not aware of a better way to do this.

**Comment by robin-nitrokey** [comment]
What about checking whether the device strings are None and printing a 
warning that suggests to install the udev rules?

I think checking whether a specific rules file is present is likely to 
cause false-positives, for example when manually installing the files or 
if a distribution changes the file name.  For example, Debian and Arch 
place the udev rules installed by libnitrokey in /usr/lib/udev/rules.d.

By the way, shouldn’t we mention the udev rules in the readme?

**Comment by szszszsz** [comment]
Why not both? I was planning to add Udev check for some time already, as a part of a general diagnostic module. We can prepare expected rules file location list for major distributions (and use `pkg-config` on the rest where available, e.g. `pkg-config  udev --variable udevdir`) and notify user about that, then possibly suggest the install command. Ideally, pynitrokey could download and install the udev rule by itself - that should not be a big problem.
Checking for the `None` results sounds good to me as well. Then the Udev rules file check could be executed.
About documenting the Udev rules requirement - yes! Could you PR that?

**Comment by robin-nitrokey** [comment]
> About documenting the Udev rules requirement - yes! Could you PR that?

Done, see #74.

**Comment by daringer** [comment]
fixed and merged, closing....
