### ISSUE TITLE
Automatic code reformat

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#8]
Run linting tools and apply suggested changes.

**Comment by szszszsz** [comment]
Some results in #9

**Comment by daringer** [comment]
the plan was to have the code nice & tidy for the release, 
but I did not have luck finding a `black` + `isort` combination that actually converges.
I mean, a configuration that leads to no changes on repeated executions.
Personally I would really prefer that this is deterministic and converging, or was this never intended?

**Comment by robin-nitrokey** [comment]
Implemented in #103.
