### ISSUE TITLE
0.4.3 sdist tarball missing on pypi.org

### ISSUE THREAD

**Issue by dvzrv** [Nitrokey/pynitrokey#87]
Hi! I would like to update the Arch Linux package to 0.4.3. Unfortunately the sdist tarball is missing on pypi.org. It would be great if you could upload it :)

**Comment by daringer** [comment]
ooops, you are fast, yes the release tag is there but the releases (including pypi and gh are not uploaded yet)... should be done by tomorrow (testing new ci/cd chain), will ping you here once it's done

**Comment by dvzrv** [comment]
Hehe, yes, I monitor my upstreams :)

Thanks! :)

**Comment by daringer** [comment]
mmmh, nearly good ...
too bad I failed again to properly tag with `.nitrokey` so I deleted, but the CI tag was not deleted ... at least it's likely that 0.4.3.1 will not clash with the origin's project versioning ... 

pypi is up to date with version 0.4.3.1: https://pypi.org/project/pynitrokey/

still some space for improvements, please close this issue if you found what's needed on pypi, thx

**Comment by dvzrv** [comment]
Thanks! I updated to 0.4.3.1
