### ISSUE TITLE
switching identity documentation

### ISSUE THREAD

**Issue by coelner** [Nitrokey/pynitrokey#94]
https://github.com/Nitrokey/pynitrokey/blob/master/README.md#switching-id

Is it possible to send the specific attribute with a scd command? Until this is done: https://github.com/Nitrokey/pynitrokey/issues/61 it can be a little bit difficult to install pynitrokey, e.g. under RPi zero and alpinelinux.

**Comment by szszszsz** [comment]
Hi!
Yes, I believe this should be possible without any problem, but unfortunately does not work for me.
The APDU is `0x85, 0x00, {ID}`, where {ID} is in range [0;2]. E.g.:
```
# id 2
$ gpg-connect-agent --hex "scd apdu  85 00 02" /bye
ERR 65539 Unknown version in packet <Unspecified source>
```

I must be missing some bytes.

**Comment by szszszsz** [comment]
Ah, yes. The `00` prefix.  Corrected. Now it works.

**Comment by szszszsz** [comment]
Fixed with https://github.com/Nitrokey/pynitrokey/commit/da508c0e61e2c5b065980b2a2c1f40dd8601982a

**Comment by szszszsz** [comment]
Add other possible scenarios. Details below:
- https://github.com/Nitrokey/pynitrokey/commit/da508c0e61e2c5b065980b2a2c1f40dd8601982a#commitcomment-55902706
